spring:
  #mysql连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/test2014
    username: root
    password: mysql2014
    driver-class-name: com.mysql.jdbc.Driver
  #redis连接信息
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
# 打印sql
logging:
  level:
     zxl.boot.cache.mybatisTest.dao: debug
