server:
  port: 8080
spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.1.102:3306/db0602
      username: zengqh
      password: 1109
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://192.168.1.103:3306/db0602
      username: zengqh
      password: 1109
      driver-class-name: com.mysql.jdbc.Driver
