server:
  port: 8132
#security:
#  basic:
#    enabled: false
spring:
  thymeleaf:
    # 配置视图路径前缀
    prefix: classpath:/templates/
    # 配置视图路径后缀
    suffix: .html
    mode: html
    # 关闭缓存 修改视图 刷新浏览器就显示 开发阶段务必关闭缓存 (=false)
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  #jpa配置
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

#配置用户名和密码
#  security:
#    user:
#      name: admin   #配置用户名
#      password: 123456   #配置密码


