spring:
  application:
    name: dubbo-consumer


embedded:
  zookeeper:
    port: 2181

dubbo:
  registry:
    address: zookeeper://192.168.1.109:2181?backup=192.168.1.109:2182,192.168.1.109:2183
    timeout: 10000

demo:
  service:
    version: 1.0.0
server:
  port: 1234